sudo: false

language: c

os:
  - linux

addons:
  apt:
    packages:
      - colorgcc
      - libucl-dev

before_script:
  - lsb_release -a
  - $TRAVIS_CC --version

script:
  - make CC=$TRAVIS_CC
  - cat input.txt | base64 --decode | ./drpdecompress | iconv -f UCS-2LE -t UTF-8//TRANSLIT > output.txt
  - grep '^XXC1|AAA0007046|.*|009002001|$' output.txt

env:
  matrix:
    - TRAVIS_CC=colorgcc EXTRA_CFLAGS='-Wall -Werror'
    - TRAVIS_CC=clang EXTRA_CFLAGS='-Wall -Werror'
    - TRAVIS_CC=clang EXTRA_CFLAGS='-std=c11 -Wall -Werror'
